// constants.js

export const GROUPS = [
  {
    groupId: "group-001",
    name: "Pizza Lovers Club",
    category: "Food",
    time: "Wednesday, 6:00 PM",
    location: "UTown Food Clique",
    members: ["Alice", "Bob", "Charlie"],
  },
  {
    groupId: "group-002",
    name: "Weekend Soccer Team",
    category: "Sports",
    time: "Saturday, 8:00 AM",
    location: "NUS Sports Field",
    members: ["David", "Eve", "Frank"],
  },
  {
    groupId: "group-003",
    name: "Math Study Group",
    category: "Study",
    time: "Monday, 7:00 PM",
    location: "Central Library Level 4",
    members: ["Grace", "Heidi", "Ivan"],
  },
  {
    groupId: "group-004",
    name: "Hackathon Warriors",
    category: "Competition",
    time: "Friday, 5:00 PM",
    location: "COM1 Seminar Room 2",
    members: ["Jack", "Karen", "Leo"],
  },
  {
    groupId: "group-005",
    name: "League of Gamers",
    category: "Gaming",
    time: "Thursday, 8:00 PM",
    location: "PGP Gaming Lounge",
    members: ["Mia", "Noah", "Olivia"],
  },
  {
    groupId: "group-006",
    name: "Saturday Night Party Squad",
    category: "Party",
    time: "Saturday, 9:00 PM",
    location: "UTown SRC Function Room",
    members: ["Paul", "Quincy", "Rachel"],
  },
  {
    groupId: "group-007",
    name: "Burger Enthusiasts",
    category: "Food",
    time: "Tuesday, 12:00 PM",
    location: "Techno Edge Canteen",
    members: ["Sam", "Tina", "Uma"],
  },
  {
    groupId: "group-008",
    name: "Morning Runners",
    category: "Sports",
    time: "Tuesday, 6:30 AM",
    location: "NUS Track Field",
    members: ["Victor", "Wendy", "Xander"],
  },
  {
    groupId: "group-009",
    name: "Physics Revision Crew",
    category: "Study",
    time: "Sunday, 2:00 PM",
    location: "Science Library Study Room",
    members: ["Yara", "Zane", "Ava"],
  },
  {
    groupId: "group-010",
    name: "Coding Challenge Champs",
    category: "Competition",
    time: "Wednesday, 7:00 PM",
    location: "Computing Club Room, COM2",
    members: ["Ben", "Cathy", "Derek"],
  },
  {
    groupId: "group-011",
    name: "Retro Game Fans",
    category: "Gaming",
    time: "Friday, 6:00 PM",
    location: "UTown Recreation Room",
    members: ["Ella", "Finn", "George"],
  },
  {
    groupId: "group-012",
    name: "Friday Night Fever",
    category: "Party",
    time: "Friday, 10:00 PM",
    location: "Sheares Hall Lounge",
    members: ["Holly", "Ian", "Julia"],
  },
  {
    groupId: "group-013",
    name: "Sushi Explorers",
    category: "Food",
    time: "Thursday, 1:00 PM",
    location: "The Spread, Mochtar Riady Building",
    members: ["Kevin", "Luna", "Max"],
  },
  {
    groupId: "group-014",
    name: "Evening Basketball Crew",
    category: "Sports",
    time: "Monday, 7:30 PM",
    location: "UTown Sports Hall",
    members: ["Nina", "Oscar", "Penny"],
  },
  {
    groupId: "group-015",
    name: "Chemistry Study Circle",
    category: "Study",
    time: "Tuesday, 3:00 PM",
    location: "SDE2 Study Pods",
    members: ["Quinn", "Ryan", "Sophia"],
  },
  {
    groupId: "group-016",
    name: "Quiz Masters League",
    category: "Competition",
    time: "Thursday, 5:30 PM",
    location: "YIH Student Lounge",
    members: ["Tom", "Ursula", "Vera"],
  },
  {
    groupId: "group-017",
    name: "Mobile Gamers Hub",
    category: "Gaming",
    time: "Wednesday, 9:00 PM",
    location: "PGP House Lounge",
    members: ["Will", "Xenia", "Yvonne"],
  },
  {
    groupId: "group-018",
    name: "Beach Party Club",
    category: "Party",
    time: "Sunday, 5:00 PM",
    location: "Cinnamon College Courtyard",
    members: ["Zack", "Abby", "Brian"],
  },
];
